# .github/workflows/metrics.yml
name: Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:

permissions:
  contents: write    # allow committing the SVG to your repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # classic token with repo + read:org
          user: ajaymahato431
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
          filename: metrics.svg

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
